export const CITIES = [
    { name: 'Батуми', slug: 'batumi' },
    { name: 'Тбилиси', slug: 'tbilisi' },
    { name: 'Кутаиси', slug: 'kutaisi' },
    { name: 'Рустави', slug: 'rustavi' },
    { name: 'Поти', slug: 'poti' },
    { name: 'Кобулети', slug: 'cities/kobuleti' },
    { name: 'Чакви', slug: 'cities/chakvi' },
    { name: 'Гонио', slug: 'cities/gonio' },
    { name: 'Квариати', slug: 'cities/kvariati' },
    { name: 'Сарпи', slug: 'cities/sarpi' },
    { name: 'Уреки', slug: 'cities/ureki' },
    { name: 'Гори', slug: 'cities/gori' },
    { name: 'Зугдиди', slug: 'cities/zugdidi' },
    { name: 'Телави', slug: 'cities/telavi' },
    { name: 'Боржоми', slug: 'cities/borjomi' },
    { name: 'Гудаури', slug: 'cities/gudauri' },
    { name: 'Степанцминда', slug: 'cities/stepantsminda' },
];
